global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "nginx_exporter"
    static_configs:
      - targets: ["nginx-prometheus-exporter:9113"]

  - job_name: "token_service"
    static_configs:
      - targets: ["token-service:5000"] # ensure token-service exposes /metrics

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"] # cadvisor container (optional)

  - job_name: "services"
    static_configs:
      - targets:
          [
            "grafana:3000",
            "loki:3100",
            "prometheus:9090",
            "nginx-prometheus-exporter:9113",
          ]
